apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: time-based-trigger
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: time-based-trigger
  name: time-based-trigger
  namespace: time-based-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: time-based-trigger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: time-based-trigger
    spec:
      containers:
      - image: phoenixop/time-based-trigger:0.0.1
        name: time-based-trigger
        resources: {}
        imagePullPolicy: Always
status: {}