# permissions for end users to edit pods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pod-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: time-based-trigger
    app.kubernetes.io/part-of: time-based-trigger
    app.kubernetes.io/managed-by: kustomize
  name: pod-editor-role
rules:
- apiGroups:
  - apps.amtd.r6security.com
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.amtd.r6security.com
  resources:
  - pods/status
  verbs:
  - get
